make guide testable

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -11,67 +11,19 @@ diff() {
     git diff --no-ext-diff --quiet
 }
 
-# Uncommitted changes
-diff || fail "Uncommitted changes"
+diff || fail "uncommitted changes"
 
-# Unformatted rust code
-cargo fmt && diff || fail "Unformatted rust code"
-cargo fmt --manifest-path crates/vk-graph-egui/Cargo.toml && diff || fail "Unformatted rust code (vk-graph-egui)"
-cargo fmt --manifest-path crates/vk-graph-fx/Cargo.toml && diff || fail "Unformatted rust code (vk-graph-fx)"
-cargo fmt --manifest-path crates/vk-graph-hot/Cargo.toml && diff || fail "Unformatted rust code (vk-graph-hot)"
-cargo fmt --manifest-path crates/vk-graph-imgui/Cargo.toml && diff || fail "Unformatted rust code (vk-graph-imgui)"
-cargo fmt --manifest-path crates/vk-graph-window/Cargo.toml && diff || fail "Unformatted rust code (vk-graph-window)"
-cargo fmt --manifest-path examples/shader-toy/Cargo.toml && diff || fail "Unformatted rust code (shader-toy)"
-cargo fmt --manifest-path examples/skeletal-anim/Cargo.toml && diff || fail "Unformatted rust code (skeletal-anim)"
-cargo fmt --manifest-path examples/vr/Cargo.toml && diff || fail "Unformatted rust code (vr)"
-
-echo "Checking vk-graph" \
-    && cargo check --all-targets || fail \
-    && cargo check --all-targets --examples || fail \
-    && cargo clippy --all-targets || fail \
-    && echo "Checking vk-graph (w/ parking_lot)" \
-    && cargo check --all-targets --features parking_lot || fail \
-    && cargo clippy --all-targets --features parking_lot || fail
-
-echo "Checking crates/vk-graph-egui" \
-    && cargo check --manifest-path crates/vk-graph-egui/Cargo.toml || fail \
-    && cargo clippy --manifest-path crates/vk-graph-egui/Cargo.toml || fail
-
-echo "Checking crates/vk-graph-fx" \
-    && cargo check --manifest-path crates/vk-graph-fx/Cargo.toml || fail \
-    && cargo clippy --manifest-path crates/vk-graph-fx/Cargo.toml || fail
-
-echo "Checking crates/vk-graph-hot" \
-    && cargo check --manifest-path crates/vk-graph-hot/Cargo.toml || fail \
-    && cargo check --manifest-path crates/vk-graph-hot/Cargo.toml --examples || fail \
-    && cargo clippy --manifest-path crates/vk-graph-hot/Cargo.toml || fail
-
-# echo "Checking crates/vk-graph-imgui" \
-#     && cargo check --manifest-path crates/vk-graph-imgui/Cargo.toml || fail \
-#     && cargo clippy --manifest-path crates/vk-graph-imgui/Cargo.toml || fail
-
-echo "Checking crates/vk-graph-window" \
-    && cargo check --manifest-path crates/vk-graph-window/Cargo.toml || fail \
-    && cargo check --manifest-path crates/vk-graph-window/Cargo.toml --examples || fail \
-    && cargo clippy --manifest-path crates/vk-graph-window/Cargo.toml || fail
-
-echo "Checking examples/shader-toy" \
-    && cargo check --manifest-path examples/shader-toy/Cargo.toml || fail \
-    && cargo clippy --manifest-path examples/shader-toy/Cargo.toml || fail
-
-echo "Checking examples/skeletal-anim" \
-    && cargo check --manifest-path examples/skeletal-anim/Cargo.toml || fail \
-    && cargo clippy --manifest-path examples/skeletal-anim/Cargo.toml || fail
-
-echo "Checking examples/vr" \
-    && cargo check --manifest-path examples/vr/Cargo.toml || fail \
-    && cargo clippy --manifest-path examples/vr/Cargo.toml || fail
-
-# Rust code tests
-cargo test || fail
+# Rust code checks
+cargo fmt && diff || fail "unformatted rust code"
+cargo check --all-targets --workspace || fail \
+    && cargo check --all-targets --features parking_lot --workspace || fail
+cargo clippy --all-targets --workspace || fail \
+    && cargo clippy --all-targets --features parking_lot --workspace || fail
+cargo test --all-targets --workspace || fail \
+    && cargo test -p guide --features hot
 
 # Build guide book
-mdbook build guide/ || fail "Unable to build guide book"
+mdbook build guide/ || fail "unable to build guide book"
 
 # Check for semver breaking changes: if this fails you must update the crate version or fix the code
 cargo semver-checks check-release --default-features
